= Javascript policy

ifdef::env-github[]
image:https://ci.gravitee.io/buildStatus/icon?job=gravitee-io/gravitee-policy-javascript/master["Build status", link="https://ci.gravitee.io/job/gravitee-io/job/gravitee-policy-javascript/"]
image:https://badges.gitter.im/Join Chat.svg["Gitter", link="https://gitter.im/gravitee-io/gravitee-io?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge"]
endif::[]

== Phase

|===
|onRequest|onResponse|onRequestContent|onResponseContent
|X|X|X|X
|===

== Description

You can use the http://www.javascript.com/[Javascript^] policy to run Javascript scripts at any stage of request processing through the gateway.

The following example Javascript script is executed during the OnResponse phase to change HTTP headers:

[source, javascript]
----
response.headers.remove('X-Powered-By');
response.headers.set('X-Gravitee-Gateway-Version', '0.14.0');
----

== Configuration

[source, json]
"javascript": {
    "onRequestScript": "response.headers.remove('X-Powered-By');",
    "onResponseScript": "response.headers.set('X-Gravitee-Gateway-Version', '0.14.0');",
    "onRequestContentScript": "" // Not executed if empty
    "onResponseContentScript": "" // Not executed if empty
}

== Usage and examples

=== onRequest / onResponse

Some variables are automatically bound to the Javascript script to allow users to use them and define the policy behavior.

[width="100%",cols="2,10",options="header"]
.List of javascript script variables
|===
| Name | Description

| `request` | Inbound HTTP request
| `response` | Outbound HTTP response
| `context` | `PolicyContext` used to access external components such as services and resources
| `result` | Javascript script result

|===

You can interrupt request or response processing by setting the result state to `FAILURE`, providing an HTTP
status code and a message (this is not mandatory, as the default status is `500 - internal server error`).

[source, javascript]
----
if (request.headers.containsKey('X-Gravitee-Break')) {
    result.state = State.FAILURE;
    result.code = 500
    result.error = 'Stop request processing due to X-Gravitee-Break header'
} else {
    request.headers.set('X-Javascript-Policy', 'ok');
}
----

To customize the error sent by the policy:

[source, javascript]
----
result.state = State.FAILURE;
result.code = 400
result.error = '{"error":"My specific error message","code":"MY_ERROR_CODE"}'
result.contentType = 'application/json'
----

=== OnRequestContent / OnResponseContent

You can also transform request or response body content by applying a Javascript script on
the `OnRequestContent` phase or the `OnResponseContent` phase.

The following example shows you how to use the Javascript policy to transform JSON content:

==== Input body content
[source, json]
----
[
    {
        "age": 32,
        "firstname": "John",
        "lastname": "Doe"
    }
]
----

==== Javascript script
[source, javascript]
----
var content = JSON.parse(response.content);
content[0].firstname = 'Hacked ' + content[0].firstname;
content[0].country = 'US';

JSON.stringify(content);
----

==== Output body content
[source, json]
----
[
    {
        "age": 32,
        "firstname": "Hacked John",
        "lastname": "Doe",
        "country": "US"
    }
]
----

== Errors

=== HTTP status code

|===
|Code |Message

| ```500```
| The Javascript script cannot be parsed/compiled or executed (mainly due to a syntax error)

|===

== Coming from Apigee

You will find below the main differences between JS scripts coming from Apigee and the one you will be able to run on the Gravitee platform:


|===
| |Apigee |Gravitee | Comment

|Access to context variables
|`context.getVariable('foo');`
|`context.attributes.foo;`
|

|Setting a context variable
|`context.setVariable('foo', 'bar');`
|`context.attributes.foo = 'bar';`
|

|Changing request or response header
|`context.targetRequest.headers['TARGET-HEADER-X']='foo';`
|`request.headers.set('TARGET-HEADER-X', 'foo');`
|`set` is used to replace the header value.

|Multivalued request or response header
|?
|`response.headers.add('TARGET-HEADER-X', 'foo');
response.headers.add('TARGET-HEADER-X', 'bar');`
|`add` can be used for multivalued headers.

|Changing response code or message
|`targetResponse.status.code = 500;`
|`response.status(500);`
|See `result` if you want to break the policy chain and return an error.

|Changing the body response
|`context.proxyResponse.content = 'foo';`
|`'foo';`
|Just set last instruction of the `OnRequestContent` to override the request body or 'OnResponseContent' to override the response body.

|Print messages
|`print('foo');`
|`print('foo');`
|The `print` statement has no effect and is simply ignored for now.

|Importing another js script
|
|
|This is not supported for now.

|Playing with request / response phases
|
`if (context.flow=="PROXY_RESP_FLOW") {
 // do something;
}`

|Use a script on each phase
|Phases are not exactly the same and gravitee does not allow to use a single script on different phases. You must define one script per phase or let the field blank if no script is necessary.

|Timeout
|`timeLimit` configuration at Javascript policy level
|
|The timeout is not supported for now.

|Manage errors
|?
|
`result.state = State.FAILURE;
result.code = 400;
result.error = '{"error":"My specific error message","code":"MY_ERROR_CODE"}';
result.contentType = 'application/json';`
|

|Http call
|`httpClient.get("http://example.com", callback);`
|`httpClient.get("http://example.com", callback);`
|/!\ This feature is a draft feature and still in development. It may evolve or not be supported in the final version.
|===

